name: gauge_cluster
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0
  flutter: ^3.29.0

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.17
  flutter_bloc: ^9.0.0
  provider: ^6.1.2
  equatable: ^2.0.7
  intl: ^0.20.2
  orbital:
    path: ../orbital

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/svgs/
    - assets/svgs/icons/
  fonts:
    - family: Tomorrow
      fonts:
        - asset: assets/fonts/Tomorrow/Tomorrow-Black.ttf
          weight: 900
        - asset: assets/fonts/Tomorrow/Tomorrow-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Tomorrow/Tomorrow-Bold.ttf
          weight: 700
        - asset: assets/fonts/Tomorrow/Tomorrow-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Tomorrow/Tomorrow-Medium.ttf
          weight: 500
        - asset: assets/fonts/Tomorrow/Tomorrow-Regular.ttf
          weight: 400
        - asset: assets/fonts/Tomorrow/Tomorrow-Light.ttf
          weight: 300
        - asset: assets/fonts/Tomorrow/Tomorrow-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Tomorrow/Tomorrow-Thin.ttf
          weight: 100
        - asset: assets/fonts/Tomorrow/Tomorrow-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/Tomorrow/Tomorrow-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Tomorrow/Tomorrow-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Tomorrow/Tomorrow-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Tomorrow/Tomorrow-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Tomorrow/Tomorrow-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Tomorrow/Tomorrow-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Tomorrow/Tomorrow-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Tomorrow/Tomorrow-ThinItalic.ttf
          weight: 100
          style: italic
